// @ts-nocheck
// This file is autogenerated by scripts/compile-block-registry.ts
// Do not edit this file directly.

import * as React from "react";

export const Index: Record<string, any> = {
  Footer1: {
    section: "footer",
    name: "Footer1",
    component: React.lazy(() => import("@/blocks/footer/Footer1.code.tsx")),
    file: {
      path: "blocks/footer/Footer1.code.tsx",
      type: "registry:block",
      target: "",
    },
  },
  Footer2: {
    section: "footer",
    name: "Footer2",
    component: React.lazy(() => import("@/blocks/footer/Footer2.code.tsx")),
    file: {
      path: "blocks/footer/Footer2.code.tsx",
      type: "registry:block",
      target: "",
    },
  },
  Hero1: {
    section: "hero",
    name: "Hero1",
    component: React.lazy(() => import("@/blocks/hero/Hero1.code.tsx")),
    file: {
      path: "blocks/hero/Hero1.code.tsx",
      type: "registry:block",
      target: "",
    },
  },
};
